# example workflow for Polaris scans using the Bridge CLI
name: polaris-bridge-cli
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: ubuntu-latest
    environment: POLARIS_SERVERURL
    env:
      BRIDGE_POLARIS_SERVERURL: ${{ vars.POLARIS_SERVERURL }}
      BRIDGE_POLARIS_ACCESSTOKEN: ${{ secrets.POLARIS_ACCESSTOKEN }}
      BRIDGE_POLARIS_ASSESSMENT_TYPES: 'SAST,SCA'
      BRIDGE_POLARIS_APPLICATION_NAME: havnoor-${{ github.event.repository.name }}
      BRIDGE_POLARIS_PROJECT_NAME: ${{ github.event.repository.name }}
      BRIDGE_POLARIS_BRANCH_NAME: ${{ github.event.ref_name }}
      BRIDGE_GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    #- name: Polaris Full Scan
    # if: ${{ github.event_name != 'pull_request' }}
    # run: |
    #    curl -fLsS -o bridge.zip https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/latest/synopsys-bridge-linux64.zip && unzip -qo -d ${{ runner.temp }} bridge.zip && rm -f bridge.zip
    #    ${{ runner.temp }}/synopsys-bridge --stage polaris \
    #        polaris.reports.sarif.create='true'
    - name: Polaris PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo ${{ github.event.base_ref }}
        echo ${{ github.repository_owner }}
        echo ${{ github.event.repository.name }}
        echo ${{ github.ref_name }}
        echo ${{ github.event.number }}
        curl -fLsS -o bridge.zip https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/latest/synopsys-bridge-linux64.zip && unzip -qo -d ${{ runner.temp }} bridge.zip && rm -f bridge.zip
        ${{ runner.temp }}/synopsys-bridge --stage polaris \
            polaris.prcomment.enabled='true' \
            polaris.branch.parent.name=${{ github.event.base_ref }} \
            github.repository.owner.name=${{ github.repository_owner }} \
            github.repository.name=${{ github.event.repository.name }} \
            github.repository.branch.name=${{ github.ref_name }} \
            github.repository.pull.number=${{ github.event.number }}
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
